import {StyleSheet} from 'react-native';


export default StyleSheet.create({
    container: {
      paddingTop:40,
      paddingLeft: 10,
      paddingRight: 10,
      flex:1,
      width: '100%',
      backgroundColor: '#4FC99A',
    },
    containerHome: {
      paddingTop:40,
      paddingBottom: 0,
      flex:1,
      backgroundColor: '#4FC99A',
      width: '100%',
      height: '100%',
    },
    areaInfo:{
      backgroundColor: '#EEFBEE',
      width:'100%',
      height: '83%',
      overflow: 'hidden',
      borderTopLeftRadius: 25,
      borderTopRightRadius: 25,
      borderLeftWidth: 0,
      flex: 1,
    },  
    bloco1:{
      backgroundColor: '#fff',
      width: '80%',
      height: '30%',
      alignContent: 'center',
      alignSelf: 'center',
      marginTop: '5%',
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 2,
      flexDirection: 'column',
      justifyContent: 'space-evenly',
    },
    parte1:{
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingLeft: 5,
      paddingRight: 5,
    },
    Item1B1:{
      flexDirection: 'row',
    },
    textoB1:{
      fontStyle: 'normal',
      fontSize: 18,
      color: '#000',
      marginTop: 5,
      marginLeft: 5,
    },
    bloco2:{
      backgroundColor: '#fff',
      width: '80%',
      height: '40%',
      alignContent: 'center',
      alignSelf: 'center',
      marginTop: '10%',
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 4,
      flexDirection: 'column',
      justifyContent: 'space-evenly'
    },
    textoB2:{
      lineHeight: 36,
      fontStyle: 'normal',
      fontSize: 24,
      color: '#000',
      justifyContent: 'center',
      alignSelf:'center',
    },
    iconeX:{
      width: 53,
      height: 52,
    },
    iconeReg:{
      width: 40,
      height: 40,
    },
    novaTela:{
      justifyContent: 'center',
      alignItems: 'flex-end',
      flexDirection: 'row',
      height: '10%',
      marginTop: '2%'
    },
    iconesB1:{
      width: 35,
      height: 35,
      marginLeft: 10,
    },
    linha:{
      borderBottomColor: 'gray',
      borderBottomWidth: 1,
    },
    textoTitulo:{
      width: '100%',
      height: 60,
      fontStyle: 'normal',
      fontWeight: 'bold',
      fontSize: 34,
      lineHeight: 36,
      color: '#FEFBFB',
      paddingTop: 15,
      paddingLeft: 10,
    },
    exibirTotal:{
      fontStyle: 'normal',
      fontSize: 24,
      lineHeight: 36,
      color: '#FEFBFB',
      justifyContent: 'center',
      alignSelf:'center',
      marginTop: 5,
      textAlign: 'center',
    },
    exibirSaldo:{
      marginTop: 7,
      marginBottom: 50,
      lineHeight: 36,
      fontStyle: 'normal',
      fontWeight: 'bold',
      fontSize: 32,
      color: '#FEFBFB',
      justifyContent: 'center',
      alignSelf:'center',
    },
    input:{
      width: '100%',
      height: 67,
      backgroundColor: 'white',
      borderRadius: 15,
      paddingLeft: 15,
      fontSize: 30,
      textAlign: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 4,
    },
    input2:{
      width: '100%',
      height: 46,
      backgroundColor: 'white',
      borderRadius: 5,
      paddingLeft: 15,
      fontSize: 25,
    },
    input3:{
      width: '40%',
      height: 46,
      backgroundColor: 'white',
      borderRadius: 5,
      paddingLeft: 15,
      fontSize: 20,
    },
    tipoOp:{
      width:'100%',
      marginTop:20,
      marginBottom: 20,
    },
    botao:{
      backgroundColor: 'rgba(52, 52, 52, 0.8)'
    },
    texto2:{
      color: '#fff',
      fontSize: 24,
      fontWeight:'bold',
      paddingLeft: 10,
    },
    viewLogin:{
      justifyContent: 'center',
      alignContent: 'center',
      alignItems: 'center',
    },
    logoLogin:{
      resizeMode: 'contain',
      width: 200,
      height: 200,
      marginBottom: 30,
      marginTop: 30, 
    },
    camposForm:{
      alignSelf: 'center',
      width: '100%',
      height: 46,
      backgroundColor: 'white',
      borderRadius: 15,
      paddingLeft: 15,
      fontSize: 25,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 4,
    },
    viewCheckbox:{
      flexDirection: 'row',
      alignItems: 'center',
    },
    checkboxTexto:{
      color: '#fff',
      fontSize: 23,
      paddingLeft: 5,
      textShadowColor: '#423f3f',
      textShadowOffset: { width:0, height: 3},
      textShadowRadius: 4,
    },
    containerLogin: {
      alignSelf: 'center',
      flex:1,
      width: '90%',
      backgroundColor: '#4FC99A',
    },
    botaoLogin:{
      backgroundColor: '#fff',
      flexDirection: 'row',
      width: 160,
      height: 50,
      alignSelf: 'center',
      marginTop: 20,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 4,
      borderRadius: 10,

    },
    textoLogin:{
      fontSize: 25,
      color: '#51c196',
      marginLeft: 10,
      fontWeight: 'bold',
    },
    iconeLogin:{
      width: 35,
      height: 35,
    },
    opcCadastro:{
      marginTop: 30,
      alignItems: 'center',
      marginBottom: 20,
    },
    txtOpcCadastro:{
      textDecorationLine: 'underline',
      color: '#fff',
      fontSize: 25
    },
    logoCadastro:{
      resizeMode: 'contain',
      width: 150,
      height: 150,
      marginBottom: 20, 
    },
    cabecalho:{
      fontSize: 30,
      marginBottom: 10,
      textAlign: 'center',
      color: '#fff',
      textTransform: 'uppercase',
    },
    topMenu:{
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 80,
    },
    micaMenu:{
      width: 200,
      height: 100,
      paddingLeft: 10,
    },
    xMenu:{
      width: 40,
      height: 40,
    },
    menuLateral:{
      width: '100%',
      paddingTop: 40,
    },
    tituloHistorico:{
      fontStyle: 'normal',
      fontSize: 50,
      color: '#FEFBFB',
      justifyContent: 'center',
      alignSelf:'center',
      marginBottom:5,
      textAlign: 'center',
      fontWeight: 'bold',
    },
    cabecalhoHistorico:{
      flexDirection:'row',
      justifyContent: 'flex-start',
    },
    iconMenuHis:{
      width:'10%',
    },
    titHistorico:{
      width: '80%',
    },
    fundoHistorico:{
      flexDirection: 'column',
      marginLeft: 10,
      marginRight: 10,
      marginTop: 20,
      paddingTop: 10,
      paddingBottom: 10,
      paddingLeft: 10,
      paddingRight: 10,
      backgroundColor: '#fff',
      borderRadius: 15
    },
    linha2:{
      borderBottomColor: 'gray',
      borderBottomWidth: 1,
      marginBottom: 10,
      marginTop: 10,
    },
    parte2:{
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignContent: 'center',
      alignItems:  'center',
      paddingLeft: 5,
      paddingRight: 5,
    },
    modal1:{
      width: '80%',
      height: '20%',
      top: '30%',
      left: '10%',
      backgroundColor: '#FFFFFF80',
      alignItems: 'center',
    },
    infoHistorico:{
      flexDirection:'row',
      marginTop: 15,
      justifyContent: 'space-between',
      padding: 10
    },
    partesInfoHistorico:{
      flexDirection: 'row',
      alignItems: 'center'
    },
    textoObjAtuais:{
      fontStyle: 'normal',
      fontSize: 24,
      lineHeight: 36,
      color: '#FEFBFB',
      marginTop: 5,
    },
    fundoObjeto:{
      flexDirection: 'column',
      width: '100%',
      height: '100%',
      marginTop: 0,
      justifyContent: 'flex-start',
      padding: 5,
      },
    parte3:{
      flexDirection: 'column',
      paddingLeft: 5,
      paddingRight: 5,
      borderRadius: 12,
      marginBottom: 5,
      backgroundColor: '#fff'
    },
    expandirObj:{
      flexDirection: 'column',
      justifyContent:'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    textoB3:{
      fontStyle: 'normal',
      fontSize: 18,
      color: '#000',
      marginTop: 5,
      marginLeft: 5,
      fontWeight: 'bold',
      marginBottom: 5
    },
    iconeObj:{
      width: 30,
      height: 30,
    },
    seletor:{
      backgroundColor: '#fff',
      fontSize: 20,
      borderRadius: 5,
      marginTop:10
    }
  });